### ISSUE TITLE
Is there a way to reflect CreateCoreWebView2EnvironmentOptions to webview2?

### ISSUE THREAD

**Issue by keiya01** [wravery/webview2-rs#10]
Thank you for creating great crates.
I have some questions.

I want to customize CreateCoreWebView2EnvironmentOptions.
And I implemented feature to create environment like the following.
This is customizing language through CreateCoreWebView2EnvironmentOptions.

```rust
CreateCoreWebView2EnvironmentCompletedHandler::wait_for_async_operation(
  Box::new(move |environmentcreatedhandler| unsafe {
    let options = {
      let options: ICoreWebView2EnvironmentOptions =
        CoreWebView2EnvironmentOptions::default().into();

      // Setting user's system language
      let lcid = Globalization::GetUserDefaultUILanguage();
      let mut lang = [0; MAX_LOCALE_NAME as usize];
      Globalization::LCIDToLocaleName(
        lcid as u32,
        &mut lang,
        Globalization::LOCALE_ALLOW_NEUTRAL_NAMES,
      );
      options
        .SetLanguage(PCWSTR(lang.as_ptr()))
        .map_err(webview2_com::Error::WindowsError)?;
      options
    };

    // remove "mini menu" - See https://github.com/tauri-apps/wry/issues/535
    let _ = options.SetAdditionalBrowserArguments("--disable-features=msWebOOUI,msPdfOOUI");
    CreateCoreWebView2EnvironmentWithOptions(
      PCWSTR::default(),
      PCWSTR::default(),
      options,
      environmentcreatedhandler,
    )
    .map_err(webview2_com::Error::WindowsError)
  }),
  Box::new(move |error_code, environment| {
    error_code?;
    tx.send(environment.ok_or_else(|| windows::core::Error::from(E_POINTER)))
      .expect("send over mpsc channel");
    Ok(())
  }),
)?;
```

And call `environment.CreateCoreWebView2Controller` then get CoreWebView2 and navigate webview2.
But My custom language is not reflected.

To resolve this problem, I think webview2 need to call `EnsureCoreWebView2Async(CoreWebView2Environment, CoreWebView2ControllerOptions)` or set environment to `CreationProperties` like [written in here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.1264.42#remarks).
Or does `webview2-com` crate reflect environment implecitly?

Thank you for reading my issue.

**Comment by keiya01** [comment]
I'm sorry I may misunderstand...

**Comment by wravery** [comment]
The `EnsureCoreWebView2Async` API is part of the WinRT wrapper around the COM APIs, that's what the doc was describing. I think the sample code you showed should work with the COM APIs and the wrappers in this crate. It should be setting that option on the environment, and then all webviews created from that environment should respect it. The `Language` property is documented here as [get_Language](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.1264.42#get_language).

You can target the WinRT wrapper with just the [windows](https://github.com/microsoft/windows-rs) crate, and it even gives you safe wrappers, which is nice. However, this crate exists and targets the unsafe COM wrappers with a custom winmd file because you can't use the WinRT wrapper on older versions of Windows. The COM APIs work all the way back to Win7 last time I tested them, but the WinRT APIs only work with Win11 or later releases of Win10 with support for the new runtime. That's also why [WRY](https://github.com/tauri-apps/wry) uses this crate, being able to target the widest range of OS versions is important for Tauri.

**Comment by keiya01** [comment]
Thank you for your reply and great description.
I see. I will research why my code is not working.

**Comment by wravery** [comment]
> @wravery Do you know the reason why [this branch](https://github.com/tauri-apps/wry/compare/feat/i18n-windows?expand=1) is not working? And if you know the reason, could you tell me about a wrong point...? Thank you for your help...

I finally had a chance to look at the branch, but it looks like it's been deleted or merged. Were you able to get it working?
