### ISSUE TITLE
How to use this `AddHostObjectToScript` method?

### ISSUE THREAD

**Issue by l1xnan** [wravery/webview2-rs#9]
I want to use [`AddHostObjectToScript`](https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2.html#method.AddHostObjectToScript) method，but I don't know how to construct `object: *mut VARIANT`. Are there any relevant examples?

**Comment by wravery** [comment]
I don't have experience with this API in particular, I usually pass data back and forth through JSON web messages. Here's the C++ [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1245.22#addhostobjecttoscript) for this method, it talks about the type constraints it imposes.

[VARIANT](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Com/struct.VARIANT.html) is a discriminated union, it has a `vt` member which determines which union member is active (the constants starting with `VT_` in [Win32::System::Ole](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Ole/index.html)). If you dig down through the "Anonymous" union types in the `windows-rs` docs, you'll find [VARIANT_0_0_0](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Com/union.VARIANT_0_0_0.html), which has the typed members for each value of `VARIANT_0_0::vt`.

To create a new `VARIANT`, call [VariantInit](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Ole/fn.VariantInit.html) (or `Default::default` would probably work), set the `vt` member, then set the corresponding union member. When you're done, free the `VARIANT` with [VariantClear](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Ole/fn.VariantClear.html), or manually drop any objects you filled in.

There's more information about `VARIANT` in the Microsoft [docs](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-variant) for C/C++.

BTW, the reason I don't use this API is that it seems to be geared primarily towards exposing [IDispatch](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-idispatch) interfaces. If you have old ActiveX or VB controls that you used to expose to the Internet Explorer webview control (a.k.a. Trident), this is a shortcut to bring that functionality into WebView2 (albeit with a different JS interface from the one in Trident). But if you're trying to implement `IDispatch` manually, it's a lot trickier, even in C/C++. It's possible, using the `windows-implement` macro, to build an object in Rust that implements [Win32::System::Com::IDispatch](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Com/struct.IDispatch.html), but it'll be at least as tricky to do that in Rust as in C++. If you're not exposing sync/async methods on the objects, and you just want to marshal data through host objects, then I find serializing to JSON and posting it as a web message is more flexible, plus it can be bi-directional since the page can post JSON messages back to an even listener in the host.

**Comment by defims** [comment]
Sometimes it’s useful to expose synchronous APIs to webviews. Since pass data back and forth through JSON is async.

**Comment by wravery** [comment]
I recently coded up a sample here: https://github.com/wravery/dispatch-graphql.

**Comment by defims** [comment]
> I recently coded up a sample here: https://github.com/wravery/dispatch-graphql.

This is a really great project that inspired me to write a [macro](https://crates.io/crates/wvwasi-macro) to automatically generate `ITypeInfo`, which simplifies the use of `AddHostObjectToScript`.
